input_features:
    -   name: ndvi
        type: timeseries
        encoder: stacked_cnn
   
    
output_features:
    -
        name: label
        type: category


training:
    batch_size: 128
    validation_metric: 'accuracy'
    early_stop: 2
    epochs: 1
    learning_rate: 0.001